/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "us-east-2:caa92bd3-3c63-4fcc-ac68-a50f6a2e2234",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_ej9IpXvt8",
    "aws_user_pools_web_client_id": "1n568ahjjeqq9lpkqheg0g7rg7",
    "oauth": {}
};


export default awsmobile;
